import{BadRequestException,ForbiddenException,Injectable,NotFoundException}from'@nestjs/common';
import{InjectRepository}from'@nestjs/typeorm';import{DataSource,In,Repository}from'typeorm';
import{Caja}from'./entities/caja.entity';import{TurnoCaja}from'./entities/turno-caja.entity';import{Sucursal}from'../branches/entities/sucursal.entity';import{Almacen}from'../warehouses/entities/almacen.entity';import{Venta}from'../sales/entities/venta.entity';
import{CreateCajaDto}from'./dto/create-caja.dto';import{UpdateCajaDto}from'./dto/update-caja.dto';import{AbrirTurnoDto}from'./dto/abrir-turno.dto';import{CerrarTurnoDto}from'./dto/cerrar-turno.dto';import{AuthenticatedUser}from'../auth/interfaces/authenticated-user.interface';import{BranchAccessService}from'../users/branch-access.service';
@Injectable()
export class PosService{
 constructor(@InjectRepository(Caja)private cajas:Repository<Caja>,@InjectRepository(TurnoCaja)private turnos:Repository<TurnoCaja>,@InjectRepository(Sucursal)private branches:Repository<Sucursal>,@InjectRepository(Almacen)private warehouses:Repository<Almacen>,private access:BranchAccessService,private dataSource:DataSource){}
 async createCaja(dto:CreateCajaDto){const sucursal=await this.branches.findOne({where:{idSucursal:dto.idSucursal}});if(!sucursal)throw new NotFoundException('Sucursal no encontrada');let almacenDefault:Almacen|null=null;if(dto.idAlmacenDefault){almacenDefault=await this.warehouses.findOne({where:{idAlmacen:dto.idAlmacenDefault}});if(!almacenDefault||almacenDefault.sucursal.idSucursal!==dto.idSucursal)throw new BadRequestException('El almacén no pertenece a la sucursal');}return this.cajas.save(this.cajas.create({sucursal,almacenDefault,codigo:dto.codigo,nombre:dto.nombre,estado:dto.estado??true}));}
 findCajas(){return this.cajas.find();} async findCajasAuthorized(actor:AuthenticatedUser){const branchIds=await this.access.accessibleBranchIds(actor);return branchIds===null?this.findCajas():this.cajas.find({where:{sucursal:{idSucursal:In(branchIds)}}});} findCajasSucursal(idSucursal:number){return this.cajas.find({where:{sucursal:{idSucursal}}});}
 async findCaja(id:number){const c=await this.cajas.findOne({where:{idCaja:id}});if(!c)throw new NotFoundException('Caja no encontrada');return c;}
 async updateCaja(id:number,dto:UpdateCajaDto){const old=await this.findCaja(id);const idSucursal=dto.idSucursal??old.sucursal.idSucursal;const sucursal=await this.branches.findOne({where:{idSucursal}});if(!sucursal)throw new NotFoundException('Sucursal no encontrada');if(dto.idAlmacenDefault){const a=await this.warehouses.findOne({where:{idAlmacen:dto.idAlmacenDefault}});if(!a||a.sucursal.idSucursal!==idSucursal)throw new BadRequestException('El almacén no pertenece a la sucursal');old.almacenDefault=a;}else if(old.almacenDefault&&old.almacenDefault.sucursal.idSucursal!==idSucursal){throw new BadRequestException('Debes seleccionar un almacén de la nueva sucursal');}old.sucursal=sucursal;if(dto.codigo!==undefined)old.codigo=dto.codigo;if(dto.nombre!==undefined)old.nombre=dto.nombre;if(dto.estado!==undefined)old.estado=dto.estado;return this.cajas.save(old);}
 async deactivateCaja(id:number){const c=await this.findCaja(id);c.estado=false;return this.cajas.save(c);}
 async abrir(actor:AuthenticatedUser,dto:AbrirTurnoDto){const caja=await this.findCaja(dto.idCaja);await this.access.assertCanAccess(actor,caja.sucursal.idSucursal);if(!caja.estado)throw new BadRequestException('La caja está inactiva');return this.dataSource.transaction(async m=>{await m.createQueryBuilder(Caja,'c').setLock('pessimistic_write').where('c.id_caja = :id',{id:caja.idCaja}).getOne();const abierto=await m.findOne(TurnoCaja,{where:{caja:{idCaja:caja.idCaja},estado:'ABIERTO'}});if(abierto)throw new BadRequestException('La caja ya tiene un turno abierto');return m.save(m.create(TurnoCaja,{caja,cajero:{idUsuario:actor.idUsuario}as any,montoApertura:dto.montoApertura,estado:'ABIERTO'}));});}
 async actual(actor:AuthenticatedUser,idCaja?:number){if(idCaja){const caja=await this.findCaja(idCaja);await this.access.assertCanAccess(actor,caja.sucursal.idSucursal);}const turno=await this.turnos.findOne({where:{cajero:{idUsuario:actor.idUsuario},estado:'ABIERTO',...(idCaja?{caja:{idCaja}}:{})}});if(!turno)throw new NotFoundException('No existe turno abierto');return turno;}
 async resolverTurno(actor:AuthenticatedUser,idSucursal:number,idCaja?:number){await this.access.assertCanAccess(actor,idSucursal);const turnos=await this.turnos.find({where:{cajero:{idUsuario:actor.idUsuario},estado:'ABIERTO',caja:idCaja?{idCaja,sucursal:{idSucursal}}:{sucursal:{idSucursal}}}});if(turnos.length!==1)throw new BadRequestException(turnos.length?'Especifica la caja del turno':'No existe un turno abierto para esta sucursal');return turnos[0];}
 async cerrar(actor:AuthenticatedUser,id:number,dto:CerrarTurnoDto){return this.dataSource.transaction(async m=>{await m.createQueryBuilder(TurnoCaja,'t').setLock('pessimistic_write').where('t.id_turno=:id',{id}).getOne();const turno=await m.findOne(TurnoCaja,{where:{idTurno:id}});if(!turno)throw new NotFoundException('Turno no encontrado');await this.access.assertCanAccess(actor,turno.caja.sucursal.idSucursal);if(turno.estado!=='ABIERTO')throw new BadRequestException('El turno ya está cerrado');if(actor.idUsuario!==turno.cajero.idUsuario&&!['ADMIN','ENCARGADO'].includes(actor.rol))throw new ForbiddenException('No puedes cerrar este turno');const raw=await m.getRepository(Venta).createQueryBuilder('v').select('COALESCE(SUM(v.total),0)','total').where('v.id_turno=:id',{id}).andWhere("v.estado='PAGADA'").getRawOne();const esperado=Number(turno.montoApertura)+Number(raw?.total??0);turno.fechaCierre=new Date();turno.montoCierreDeclarado=dto.montoCierreDeclarado;turno.montoCierreEsperado=esperado;turno.diferencia=Number(dto.montoCierreDeclarado)-esperado;turno.estado='CERRADO';return m.save(turno);});}
}
