export type TipoTryOn = 'lentes' | 'gorra' | 'polera'
export type TipoPrendaVestidor = 'GORRA' | 'SOMBRERO' | 'CAMISA' | 'BLUSA' | 'TOP' | 'PANTALON' | 'VESTIDO_CORTO' | 'VESTIDO_LARGO' | 'FALDA_CORTA' | 'FALDA_LARGA' | 'COLLAR' | 'CARTERA' | 'BUFANDA' | 'VESTIDO' | 'FALDA' | 'OTRO'
export interface CatalogItem { idCategoria?: number; idTalla?: number; idColor?: number; idTemporada?: number; idColeccion?: number; idProveedor?: number; nombre: string; descripcion?: string; codigoHex?: string; estado?: boolean }
export interface CatalogRecord { idCategoria?: number; idTalla?: number; idColor?: number; idTemporada?: number; idColeccion?: number; idProveedor?: number; nombre: string; descripcion?: string; codigoHex?: string; estado?: boolean }
export interface Producto extends CatalogRecord { idProducto: number; categoria?: CatalogRecord; precio: number | string; precioMayorista?: number | string | null; cantidadMinimaMayorista?: number | null; imagenUrl?: string; imagenCatalogoUrl?: string | null; imagenVestidorUrl?: string | null; recursoRaUrl?: string; imagenTryOn?: string | null; tipoTryOn?: TipoTryOn | null; tipoPrendaVestidor?: TipoPrendaVestidor | null; variantes?: Variante[]; sucursalOrigen?: { idSucursal: number } | null }
export interface Variante { idVariante: number; idProducto?: number; idTalla?: number; idColor?: number; sku: string; estado?: boolean; producto?: Producto; talla?: CatalogRecord | null; color?: CatalogRecord | null; imagenVestidorUrl?: string | null; imagenes?: ImagenVariante[] }
export interface ImagenVariante { idImagen: number; url: string; orden: number; principal: boolean; tipo?: string; transparente?: boolean }
export interface CreateProductoRequest extends CatalogItem { idSucursal?: number; idCategoria: number; precio: number; idProveedor?: number; idColeccion?: number; imagenUrl?: string; imagenCatalogoUrl?: string; imagenVestidorUrl?: string | null; tipoPrendaVestidor?: TipoPrendaVestidor | null; recursoRaUrl?: string; imagenTryOn?: string | null; tipoTryOn?: TipoTryOn | null; precioMayorista?: number; cantidadMinimaMayorista?: number }
export interface CreateVarianteRequest { idSucursal?: number; idProducto: number; idTalla?: number; idColor?: number; sku: string; imagenVestidorUrl?: string | null }
